### ISSUE TITLE
Syntax highlighting?

### ISSUE THREAD

**Issue by nexxeln** [kkga/ter#10]
Would be cool to have some syntax highlighting out of the box matching the whole theme.

**Comment by kkga** [comment]
There is syntax highlighting, although quite minimal. Do you need a specific theme?
<img width="738" alt="image" src="https://user-images.githubusercontent.com/1460122/176642205-36b08313-bc7f-4a1b-ae4a-0341e6b64455.png">

**Comment by nexxeln** [comment]
Yeah its def very minimal. I would like a bit more but within the same theme

**Comment by nexxeln** [comment]
here there is no syntax highlighting.

![ss](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/brave_BVOgyaFMZs.png)

**Comment by trickster** [comment]
Minimal dark syntax highlighting would be amazing.
