### ISSUE TITLE
RSS feed not working?

### ISSUE THREAD

**Issue by tiagojacinto** [kkga/ter#13]
Hello, is there any problem with the generation of the rss feed? It keeps showing my this: XML Parsing Error: mismatched tag. Expected: </link>.
Could it be an error on my config?

**Comment by kkga** [comment]
Yes, it seems I broke the XML template in of the recent updates. I'll take a look this weekend. Do you need just a global feed for the whole site or individual feeds based on directories? I might add directory-based feeds as well.

**Comment by tiagojacinto** [comment]
I think that a global feed is enough, but directory-based feeds are very tempting 👍 (blog, photolog, etc)
Thanks!

**Comment by kkga** [comment]
The global feed should now be working with the latest release.
Keep in mind that there is a breaking change that requires to migrate the YAML configuration file to JSON: https://github.com/kkga/ter/releases/tag/0.7.0

**Comment by tiagojacinto** [comment]
It works! Thanks!
(both the rss feed and the updated config file)
