### ISSUE TITLE
Differentiate internal and external links

### ISSUE THREAD

**Issue by almereyda** [kkga/ter#41]
Clicking a link can sometimes make me leave the page, when I just wanted to explore the site.

Would it be possible to find a non-intrusive, conventional indicator for differentiating internal and external links?

**Comment by kkga** [comment]
I've had arrow symbols next to external links previously (↗), but wasn't happy with how it looked. What would work for you?

**Comment by almereyda** [comment]
One way could be to leave external links blue, and have internal links render in the text colour, but also underlined. Or to have dashed (external) and complete (internal) underlines for differentiation. If in the same colour, internal and external links could also be differentiated by boldness (text weight). Of course this is a highly debated subject.

I agree, that `arrow_upper_right` is not the final answer. But then there's also [🔗](https://symbl.cc/en/1F517/), but not much more useful, as it's also coloured.

I believe common external link symbols look like what's presented in https://www.unicode.org/L2/L2018/18303-external-link.pdf and what we know from Wikipedia and other icon fonts, such as Font Awesome or the Noun project.

Maybe it's possible to find a nice icon with good proportions that works well in the font, add its SVG as a data URL to the CSS?

If the indication should be as unintrusive as possible, I guess no icon, but font styling differences could work, as icons often want to be seen, and come with a lot of detail that can distract the eye.

**Comment by kkga** [comment]
Let's use the `↗` suffix on external links, looks like the most optimal approach.
