### ISSUE TITLE
Incorrectly index when folder name is not English

### ISSUE THREAD

**Issue by thangisme** [kkga/ter#51]
If I name my folder in Vietnamese, I'd build two different folder . For example, "Việt Nam" would be "Viet-Nam" and the original name. However, the index web page will link to the url point at "Viet-Nam" folder while "Việt Nam" folder is where all content are built . Accessing url at "Việt Nam" return 404 even if that folder exist

**Comment by kkga** [comment]
I can't at the moment. Contributions welcome.
